### ISSUE TITLE
Error when converting file containing { }

### ISSUE THREAD

**Issue by SMayer135** [mrlacey/ResPsuedoLoc#24]

**Comment by mrlacey** [comment]
@SMayer135 what's the error you're encountering?

I've done a quick check and when I put "{}" inside a resource I see that the following aren't working properly.

- Can't toggle (to remove) diacritics
- "DDoouubbllee" doesn't work

Is one of these the issue you're seeing?

**Comment by lokarithm** [comment]
I added a localized string with a string {myToken} to be replaced after getting the value of the string. For example, the whole string is "some text {myToken} end string". I want to replace the {myToken} to be a user name later. After toggling, I manually updated the toggled text(just for {myToken})to plain text. I see this error in the screenshot below. I learned that Pseudo Localize currently probably doesn't support marking a particular part of a string to be excluded from toggling. This can be a feature. But looks like there is a bug toggling the curly brackets in general.
![image](https://user-images.githubusercontent.com/1385766/120535429-f6f76180-c3b0-11eb-857b-63838be0ae4a.png)

**Comment by mrlacey** [comment]
@lokarithm I can't recreate the issue you're seeing.

Does it happen with a new resource file with just that single entry in it?

Which version of visual studio are you using?
Which version of the extension is installed?
What project type do you have? (WPF, WinUI, UWP, Xamarin.Forms, something else...)
Which pseudo-localization option are you using?

**Comment by mrlacey** [comment]
I've been unable to reproduce the issue as reported. 
However, I've just released version 3.2 to the marketplace and this has some improvements that may address the problem.

Please can you try updating to this new version and seeing if the problem still exists.
If the problem does still persist, please can you provide the following to allow me to investigate further:

- Does it happen with a new resource file with just that single entry in it?
- Which version of visual studio are you using?
- Which version of the extension is installed?
- What project type do you have? (WPF, WinUI, UWP, Xamarin.Forms, something else...)
- Which pseudo-localization option are you using?

If I can solve the cause of the problem, I'll then look at excluding text within curly braces from being pseudo-localized.

**Comment by lokarithm** [comment]
> @lokarithm I can't recreate the issue you're seeing.
> 
> Does it happen with a new resource file with just that single entry in it?
> 
> Which version of visual studio are you using?
> Which version of the extension is installed?
> What project type do you have? (WPF, WinUI, UWP, Xamarin.Forms, something else...)
> Which pseudo-localization option are you using?

Hey Matt, thanks for the quick reply and update! I updated the extension and still can reproduce the issue.
I'm on Visual Studio Professional 2019 and the latest version of the extension(v3.2).

This is how my resx file looks like:
![image](https://user-images.githubusercontent.com/1385766/120862103-6195d200-c556-11eb-9fc9-d1a99376f17e.png)

And this is the toggle option I have picked:
![image](https://user-images.githubusercontent.com/1385766/120862129-6fe3ee00-c556-11eb-9920-959f4cffbef4.png)

To reproduce the issue:
1. Type in "Some text more text" as value, the name doesn't matter
2. Toggle with the second option, now you should have "S̮̆ŏ̮m̮̆ĕ̮ t̮̆ĕ̮x̮̆t̮̆ m̮̆ŏ̮r̮̆ĕ̮ t̮̆ĕ̮x̮̆t̮̆" as value
3. Add "{token}" to the value, so it ends up as "S̮̆ŏ̮m̮̆ĕ̮ t̮̆ĕ̮x̮̆t̮̆ {token} m̮̆ŏ̮r̮̆ĕ̮ t̮̆ĕ̮x̮̆t̮̆". The string in between the curly brackets doesn't matter.
4. Toggle with the same option and you should see the error below
![image](https://user-images.githubusercontent.com/1385766/120862378-d832cf80-c556-11eb-9e3d-af85e0e16bac.png)

**Comment by mrlacey** [comment]
@lokarithm thanks for the information.
I've found and fixed the cause of the problem and released a new version (3.3) that has the fix.

I'll add a separate update (hopefully soon) that adds the option to exclude any text between curly braces.

**Comment by SMayer135** [comment]
Thanks @mrlacey that resolved the problem for us. The string interpolation option will be very helpful!
